import { jsPDF } from 'jspdf'

export function generatePaymentUrl(invoiceId, invoiceNumber) {
  const baseUrl = window.location.origin
  return `${baseUrl}/pay/${invoiceId}`
}
export function generateInvoicePDF(invoice, clientName, businessName, ownerName) {
  const doc = new jsPDF()
  const green = [0, 197, 102]
  const dark = [8, 12, 10]
  const grey = [138, 158, 146]
  const white = [240, 245, 242]

  // Background
  doc.setFillColor(...dark)
  doc.rect(0, 0, 210, 297, 'F')

  // Header bar
  doc.setFillColor(15, 21, 16)
  doc.rect(0, 0, 210, 45, 'F')

  // Brand name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.setTextColor(...white)
  doc.text('Stack', 20, 28)
  doc.setTextColor(...green)
  doc.text('Pay', 47, 28)

  // Invoice label
  doc.setFontSize(11)
  doc.setTextColor(...grey)
  doc.setFont('helvetica', 'normal')
  doc.text('INVOICE', 150, 20)
  doc.setFontSize(14)
  doc.setTextColor(...white)
  doc.setFont('helvetica', 'bold')
  doc.text(invoice.invoice_number, 150, 30)

  // Status badge
  const statusColor = invoice.status === 'paid' ? green : [245, 166, 35]
  doc.setFillColor(...statusColor)
  doc.roundedRect(150, 34, 30, 8, 2, 2, 'F')
  doc.setFontSize(8)
  doc.setTextColor(8, 12, 10)
  doc.setFont('helvetica', 'bold')
  doc.text(invoice.status.toUpperCase(), 160, 39.5)

  // Business info
  doc.setFontSize(10)
  doc.setTextColor(...grey)
  doc.setFont('helvetica', 'normal')
  doc.text('FROM', 20, 60)
  doc.setFontSize(12)
  doc.setTextColor(...white)
  doc.setFont('helvetica', 'bold')
  doc.text(businessName || 'Your Business', 20, 68)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...grey)
  doc.text(ownerName || '', 20, 75)

  // Client info
  doc.setFontSize(10)
  doc.setTextColor(...grey)
  doc.text('BILL TO', 120, 60)
  doc.setFontSize(12)
  doc.setTextColor(...white)
  doc.setFont('helvetica', 'bold')
  doc.text(clientName || 'Client', 120, 68)

  // Dates
  doc.setFontSize(9)
  doc.setTextColor(...grey)
  doc.setFont('helvetica', 'normal')
  doc.text(`Issue Date: ${new Date(invoice.created_at).toLocaleDateString('en-NG')}`, 20, 88)
  if (invoice.due_date) {
    doc.text(`Due Date: ${new Date(invoice.due_date).toLocaleDateString('en-NG')}`, 20, 95)
  }

  // Divider
  doc.setDrawColor(...green)
  doc.setLineWidth(0.5)
  doc.line(20, 102, 190, 102)

  // Table header
  doc.setFillColor(20, 26, 22)
  doc.rect(20, 106, 170, 10, 'F')
  doc.setFontSize(9)
  doc.setTextColor(...grey)
  doc.setFont('helvetica', 'bold')
  doc.text('DESCRIPTION', 25, 113)
  doc.text('QTY', 120, 113)
  doc.text('PRICE', 140, 113)
  doc.text('TOTAL', 168, 113)

  // Items
  let y = 125
  const items = invoice.items || []
  items.forEach((item, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(15, 21, 16)
      doc.rect(20, y - 6, 170, 10, 'F')
    }
    doc.setFontSize(10)
    doc.setTextColor(...white)
    doc.setFont('helvetica', 'normal')
    const desc = item.description?.length > 35
      ? item.description.substring(0, 35) + '...'
      : item.description
    doc.text(desc || '', 25, y)
    doc.text(String(item.quantity || 1), 122, y)

    const price = Number(item.price || 0)
    const qty = Number(item.quantity || 1)
    const lineTotal = price * qty

    doc.text(`₦${price.toLocaleString()}`, 138, y)
    doc.text(`₦${lineTotal.toLocaleString()}`, 166, y)
    y += 12
  })

  // Totals section
  y += 5
  doc.setDrawColor(...green)
  doc.setLineWidth(0.3)
  doc.line(120, y, 190, y)
  y += 10

  doc.setFontSize(10)
  doc.setTextColor(...grey)
  doc.text('Subtotal', 120, y)
  doc.setTextColor(...white)
  doc.text(`₦${Number(invoice.subtotal || 0).toLocaleString()}`, 166, y)
  y += 9

  doc.setFontSize(12)
  doc.setTextColor(...green)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL', 120, y)
  doc.text(`₦${Number(invoice.total || 0).toLocaleString()}`, 163, y)

  // Notes
  if (invoice.notes) {
    y += 20
    doc.setFontSize(9)
    doc.setTextColor(...grey)
    doc.setFont('helvetica', 'normal')
    doc.text('NOTES', 20, y)
    y += 7
    doc.setTextColor(200, 210, 205)
    const lines = doc.splitTextToSize(invoice.notes, 160)
    doc.text(lines, 20, y)
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(...grey)
  doc.text('Generated by StackPay — stackpay-five.vercel.app', 20, 285)
  doc.setTextColor(...green)
  doc.text('Thank you for your business!', 130, 285)

  doc.save(`${invoice.invoice_number}.pdf`)
}
